### PR TITLE
Rename SectionName to BpfFunctionName in bpfd CRDs

### PR DESCRIPTION
**Pull request by anfredette**
Since we no longer load BPF files based on their section name, the CRD field `SectionName` is no longer correct.  So, we decided to rename the field to `BpfFunctionName`, with a description of "the name of the function that is the entry point for the BPF program.

This had a pretty big ripple effect through the code since pretty much everywhere we referenced some variant of "section name" was wrong and needed to be changed to a similar variant of "bpf fn name"

This results in the following changes:
```
SectionName  => BpfFunctionName
sectionname  => bpffunctionname
sectionName  => bpfFunctionName
SECTIONNAME  => BPFFUNCTIONNAME
SECTION_NAME => BPF_FUNCTION_NAME
section_name => bpf_function_name
```

### CODE REVIEW

**Comment by anfredette** [comment]
These changes require all of our images to be rebuilt with the new io.ebpf.bpf_fn_name tag.  Therefore, many of the tests that need to pull images from quay will fail.  I successfully ran integration tests from images I built with build_push_images.sh (both modified to use my personal quay repos).

I didn't want to update the images until people have had a chance to look at the changes.

It's probably redundant, but I put a hold label on this pr until we're all good and ready to push new images.

**Review by astoycos — APPROVED** [review]
These LGTM but I want @dave-tucker to be alright before we merge so please leave the hold on here until then. 👍

**Comment by Billy99** [comment]
@anfredette #754 added a few more SECTION_NAME to [.github/workflows/image-build.yaml](https://github.com/bpfd-dev/bpfd/pull/754/files#diff-502adaf7a495a56eb3ecef9c7f4c295ce0ac343f9b0d4e2fd321910fdf8f58bd), so make sure you get those.

**Comment by anfredette** [comment]
> @anfredette #754 (and #760 if it goes in first) added a few more SECTION_NAME to [.github/workflows/image-build.yaml](https://github.com/bpfd-dev/bpfd/pull/754/files#diff-502adaf7a495a56eb3ecef9c7f4c295ce0ac343f9b0d4e2fd321910fdf8f58bd), so make sure you get those.

Done

**Comment by anfredette** [comment]
The change to BpfFunctionName has been made.  We'll need to push new bytecode images to https://quay.io/repository/bpfd-bytecode before the integration tests and some others will pass.

**Review by astoycos — APPROVED** [review]
LGTM

**Pull request merged**
