### PR TITLE
Cut release V0.2.1

### PR DESCRIPTION
**Pull request by astoycos**
See change log for details

### CODE REVIEW

**Comment by astoycos** [comment]
So action's won't run here :( @dave-tucker @anfredette Even if they did I don't think they'd run agains't this branches workflow files but I'll need to check that

**Review by anfredette — CHANGES_REQUESTED** [review]
Should we give the xdp dispatchers a "0.2.1" tag?

Should the other images that are tagged "0.2.0" be tagged "0.2.1"?

**Comment by astoycos** [comment]
```
  BPFD_REPOSITORY: bpfd
  BPFD_USERSPACE_REPOSITORY: bpfd-userspace
  BPFD_BYTECODE_REPOSITORY: bpfd-bytecode
  BPFD_IMAGE_NAME: bpfd
  BPFCTL_IMAGE_NAME: bpfctl
  BPFD_AGENT_IMAGE_NAME: bpfd-agent
  BPFD_OPERATOR_IMAGE_NAME: bpfd-operator
  BPFD_OPERATOR_BUNDLE_IMAGE_NAME: bpfd-operator-bundle
  GO_XDP_COUNTER_IMAGE_NAME: go-xdp-counter
  GO_TC_COUNTER_IMAGE_NAME: go-tc-counter
  GO_TRACEPOINT_COUNTER_IMAGE_NAME: go-tracepoint-counter
```

Are all the images which will be built/pushed with the new v0.2.1 tag once It's pushed up (following the merge of this PR)

**Comment by anfredette** [comment]
> > Should we give the xdp dispatchers a "0.2.1" tag?
> 
> I don't think so... Maybe in v0.3.0 we can change to doing that (which should come soon) but I think mucking around with this old brach isn't worth it.... Also in v0.2.0 we didn't even build the dispatchers in CI
> 

I'm fine with that.

**Review by anfredette — APPROVED** [review]
lgtm

**Pull request merged**
