### PR TITLE
Relicense userspace to Apache 2.0 only

### PR DESCRIPTION
**Pull request by dave-tucker**
This is simply dropping requirement for inbound contributions to be MIT licensed + removal of outbound option of MIT.

As all contributions are already submitted under both licenses this shouldn't be controversial. The reasoning for this is to simply our license arrangement before submitting to the CNCF sandbox.

At some point in future we might revisit this and look to provide MIT as an outbound option again - which is very common in the Rust ecosystem.

### CODE REVIEW

**Comment by dave-tucker** [comment]
Contributors, please add an LGTM here to acknowledge the license change and feel free to ping me here (or via Slack/Discord) if you have any questions:

- @astoycos 
- @Billy99 
- @anfredette 
- @nerdalert 
- @Molter73 
- @nak3 
- @shaneutt 
- @ykaliuta 
- @maryamtahhan 
- @navarrothiago

**Comment by ykaliuta** [comment]
> Contributors, please add an LGTM here to acknowledge the license change and feel free to ping me here (or via Slack/Discord) if you have any questions:
> 
> * @ykaliuta

LGTM

**Comment by dave-tucker** [comment]
That's a full set of LGTMs so I'll go ahead and merge this - Andre's was verbal in the last bpfd maintainers meeting but he can comment here once he's back to complete the audit trail.

**Review by anfredette — COMMENTED** [review]
LGTM

**Pull request merged**
