### PR TITLE
Add examples for tc, and setting globals and proceed-on

### PR DESCRIPTION
**Pull request by anfredette**

### CODE REVIEW

**Review by Billy99 — COMMENTED** [review]
Thanks Andre. I like the content. Thinking we should move it down under individual headings. I'll add more sections over time as functionality grows.

**Comment by anfredette** [comment]
@Billy99 thanks for the comments.  I think I made the updates you suggested, but I'm planning to add a little more description to the proceed-on.  So, I put a hold on this while I'm doing that.

**Comment by anfredette** [comment]
@Billy99, I made a few more tweaks.  Please take another look when you have a chance.

**Review by Billy99 — APPROVED** [review]
LGTM

**Pull request merged**
